name: Build - Emscripten

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  job:
    name: emscripten-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Get vcpkg commit ID
        id: vcpkg-step
        run: |
          vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')
          echo "vcpkg commit ID: $vcpkgCommitId"
          echo "vcpkgGitCommitId=$vcpkgCommitId" >> $GITHUB_OUTPUT

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: |
          cmake -G Ninja -S . -B build \
            -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=wasm32-emscripten \
            -DVCPKG_OVERLAY_PORTS=${{ github.workspace }}/browser/overlay-ports \
            -DCMAKE_MAKE_PROGRAM=ninja \
            -DOPTIONS_ENABLE_IPO=OFF \
            -DTOGGLE_BIN_FOLDER=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DTOGGLE_BOT_PROTECTION=OFF

      - name: Build
        run: cmake --build build

      - name: Create and Upload Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: otclient-emscripten-release-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/otclient.*